### ISSUE TITLE
Align with new heroku pricing plans

### ISSUE THREAD

**Issue by Hronom** [davidji99/terraform-provider-herokux#301]
Hi there,

### What is the nature of the issue? (Check all that may apply)
- [ ] Bug
- [ ] Feature
- [x] Enhancement

### Expected Behavior
Heroku release [new pricing plans](https://www.heroku.com/pricing), please adjust them accordingly.
For example here need to allow `Basic` instead of `Free`:
```
resource "herokux_scheduler_job" "ggg_schedule_job" {
  app_id    = heroku_app.ggg.uuid
  command   = "ggg"
  dyno_size = "Basic"
  frequency = "every_day_at_13:00"
}
```

### Actual Behavior
```
Terraform will perform the following actions:

  # herokux_scheduler_job.ggg_schedule_job will be updated in-place
  ~ resource "herokux_scheduler_job" "ggg_schedule_job" {
      ~ dyno_size   = "Basic" -> "Free"
        id          = "xxx"
        # (4 unchanged attributes hidden)
    }
```

**Comment by davidji99** [comment]
I don't think 'Basic' is a valid plan name option for the scheduler. Trying this out in the UI, I can only see 'Standard - Free'.

I'm also surprised that you were able to create the schedular job resource with `dyno_size = "Basic"` because there's validation for the `dyno_size` attribute and 'Basic' is not one of the options.

**Comment by Hronom** [comment]
@davidji99 `Basic` it's a name for a used [Dyno](https://devcenter.heroku.com/articles/usage-and-billing#dyno-usage-and-costs) by scheduler. It's not scheduler [type](https://elements.heroku.com/addons/scheduler).

Also I actually created with `Free` plan:
```
resource "herokux_scheduler_job" "xxx_schedule_job" {
  app_id    = heroku_app.xxx.uuid
  command   = "java -Dspring.profiles.active='prod, upload' -jar ./xxx/target/*.jar"
  dyno_size = "Free"
  frequency = "every_day_at_13:00"

  lifecycle {
    ignore_changes = [
      dyno_size
    ]
  }

  depends_on = [
    heroku_addon.scheduler
  ]
}
```
Heroku automatically save it as Basic, so later on if you re-apply script it will think that there a change.

The dyno size names is [here](https://devcenter.heroku.com/articles/usage-and-billing#dyno-usage-and-costs) 
```
Eco
Basic
Standard-1X
Standard-2X
Performance-M
Performance-L
```
