### ISSUE TITLE
Postgres Credentials API may have changed.

### ISSUE THREAD

**Issue by dougbradbury** [davidji99/terraform-provider-herokux#321]
Hi there,

### What is the nature of the issue? (Check all that may apply)
- [x] Bug
- [ ] Feature
- [ ] Enhancement

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Provider Versions
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v1.5.1
on darwin_amd64
+ provider registry.terraform.io/davidji99/herokux v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `"herokux_postgres_credential`

### Terraform Configuration Files
```hcl
resource "herokux_postgres_credential" "app" {
  postgres_id = var.database-add-on-id
  name        = "core-services-app-credentials"
}
```

### Debug Output
https://gist.github.com/dougbradbury/6d35aa556e129a471618438349c1b2cf

### Panic Output
None

### Expected Behavior
When running a plan,
The current state of the credentials should have been queried and no change detected

### Actual Behavior
What actually happened?
 Error: GET https://postgres-api.heroku.com/postgres/v0/databases/b6a7aadb-b778-45fc-8124-1fe153b3b2ef/credentials/core-services-app-credentials: 404 {"id":"not_found","message":"Couldn't find that add-on."}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
This has started happening sometime in the past 6 days.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by davidji99** [comment]
Hmmm, interesting. I'll have to investigate this!

**Comment by davidji99** [comment]
From the use of the chrome inspector, it seems this postgres credential endpoint has moved to using GraphQL.
