### ISSUE TITLE
herokux_postgres_backup_schedule only accepts UUID - which seems to break with recent addons

### ISSUE THREAD

**Issue by vseguin** [davidji99/terraform-provider-herokux#374]
Hi there,

### What is the nature of the issue? (Check all that may apply)
- [X] Bug
- [ ] Feature
- [ ] Enhancement

### Terraform Version
1.7.1

### Provider Versions
1.4.0

### Affected Resource(s)
`herokux_postgres_backup_schedule`

### Terraform Configuration Files
```
resource "heroku_addon" "database" {
  app_id = heroku_app.app.id
  plan   = "heroku-postgresql:${var.database_size}"
}

resource "herokux_postgres_backup_schedule" "database_backup_schedule" {
  postgres_id = heroku_addon.database.id
  hour        = 4
  timezone    = "America/Los_Angeles"
}
```

### Expected Behavior
I have been following the documentation here to terraform a backup schedule for an existing add-on. I would expect it to work - but it seems that `heroku_addon.database.id` actually returns the addon_id instead of the expected UUID.

### Actual Behavior
I get the following
```
│ Error: expected "postgres_id" to be a valid UUID, got postgresql-elliptical-83771
│ 
│   with module.heroku_app["hackerone"].herokux_postgres_backup_schedule.database_backup_schedule,
│   on modules/app/heroku/main.tf line 124, in resource "herokux_postgres_backup_schedule" "database_backup_schedule":
│  124:   postgres_id = heroku_addon.database.id
```

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`

**Comment by davidji99** [comment]
THanks for reporting this @vseguin. I'll take a look. Heroku might have changed the underlying API since the resource was implemented 3 years ago.

**Comment by vseguin** [comment]
Wonderful @davidji99, thank you very much!
