### ISSUE TITLE
pg:backups:schedule for Starter Plans

### ISSUE THREAD

**Issue by dimasusername** [davidji99/terraform-provider-herokux#69]
Hi there,

### Terraform Version
Terraform v0.13.6

### HerokuX Provider Version
0.17.1

### Affected Resource(s)
Please list the resources as a list, for example:
- herokux_postgres_backup_schedule

### Detail

As described in the docs, current implementation won't work with starter plans.

The reason is that https://postgres-api.heroku.com/client/v11/databases endpoint works with professional plans and up.

However, there is another endpoint for starter plans: https://postgres-starter-api.heroku.com/client/v11/databases

Is there any way this could be incorporated into the provider, so we can use it to set up schedules for databases on starter plans, too?

**Comment by davidji99** [comment]
Hi @dimasusername,

Thanks for the issue! It is possible to use `herokux_postgres_backup_schedule` resource for PG starter plans by setting [`postgres_api_url` attribute](https://registry.terraform.io/providers/davidji99/herokux/latest/docs#postgres_api_url) to ` https://postgres-starter-api.heroku.com`. If you have a mix starter and standard PG databases within one terraform configuration, you could make use of [provider aliases](https://www.terraform.io/docs/language/providers/configuration.html).

**Comment by dimasusername** [comment]
Hi @davidji99,

Thanks a lot for a prompt response! I apologise for not reading the docs in full and missing this! 🙌

**Comment by davidji99** [comment]
No worries!
